import type { ArticlePage } from "./pages";

type Override = Partial<ArticlePage>;

export const hubContentOverrides: Record<string, Override> = {
  "start-here": {
    intro: "I use this page to start with the decision currently blocking the business: finding a product, validating demand, understanding competitors, researching ads, choosing a platform workflow or removing repetitive operations. Each path below ends at a complete guide or tool comparison rather than an open-ended software directory.",
    verdict: "I recommend beginning with platform-native data and one focused research workflow. I would add software only when it answers a recurring question, produces a reusable output and has a named owner.",
    sections: [
      { heading: "Before Choosing a Tool", paragraphs: ["I first write the target market, platform, business model, monthly research volume and the decision the tool must support. A TikTok Shop seller researching creators needs a different system from a Shopify media buyer studying Meta ads or an Amazon operator improving listings.", "I then add non-negotiable requirements such as countries, history, exports, seats and integrations. This one-page requirement prevents a vendor demo from redefining the problem, and it gives me a consistent basis for rejecting a tool that looks impressive but does not fit the workflow."] },
      { heading: "Path 1: Find and Validate a Product", paragraphs: ["For TikTok Shop, begin with the product-research guide and compare Kalodata, FastMoss and Shoplus. Kalodata has publicly documented category, product, shop, creator, video and livestream routes. FastMoss needs a live known-entity test. Shoplus is most clearly positioned for video, music, ads and influencer research.", "For Shopify or ad-led discovery, compare WinningHunter and Minea. Then move the shortlist into landed margin, supplier, review, policy and fulfillment checks before ordering inventory."] },
      { heading: "Path 2: Understand Competitors", paragraphs: ["Choose the competitor entity first: product, marketplace shop, Shopify store, creator or advertiser. Use a TikTok Shop platform for marketplace entities and WinningHunter or Minea for ads and Shopify-oriented store research.", "Record public facts, vendor estimates and operator conclusions separately. Competitor revenue, traffic and ad-spend numbers should never be reported as confirmed internal data."] },
      { heading: "Path 3: Research Ads and Creative", paragraphs: ["Use known advertisers to test WinningHunter and Minea before relying on discovery results. Compare channel coverage, active and historical ads, dates, landing pages, store connections and exports.", "The final output is an original creative brief with verified product claims. Do not copy scripts, footage, layouts or brand assets from ads discovered in a research platform."] },
      { heading: "Path 4: Build Platform Operations", paragraphs: ["TikTok Shop combines marketplace, creator, content and fulfillment operations. Amazon depends heavily on Seller Central, listings, advertising and inventory. Shopify gives teams more freedom to combine apps, email, creative and automation.", "Keep platform-native account data as the source of truth. External intelligence helps prioritize questions but should not overwrite settlements, order records or platform policy."] },
      { heading: "Path 5: Add AI and Automation", paragraphs: ["Begin with a low-risk task such as source-based research synthesis or first-draft content. Define the reviewer and failure consequence before choosing a model. Add automation only when the manual process, exceptions and recovery steps are documented."] },
      { heading: "Your First 30 Days", bullets: ["Week 1: document markets, decisions and current tools", "Week 2: trial one research category with known entities", "Week 3: validate one shortlist with margin and supplier evidence", "Week 4: review approved output, cost and remaining manual work"] },
      { heading: "When to Add Another Subscription", paragraphs: ["I would add a second tool when it answers a separate recurring question or demonstrably improves retrieval, history, exports or collaboration. I would not retain two overlapping products because each found a different impressive example during a sales demo.", "I recommend reviewing subscriptions quarterly and recording the reason for renewal. If the owner or output no longer exists, cancel the subscription or redesign the process before paying for another period."] },
    ],
    faqs: [
      { question: "Which ecommerce tool should a new seller buy first?", answer: "Start with platform-native reporting and one focused research system matched to the first recurring decision. Do not buy a broad stack before the workflow is defined." },
      { question: "Where should TikTok Shop product research begin?", answer: "Begin with category and known-product research, then connect candidates to shops, creators, videos and livestreams before margin and supplier validation." },
      { question: "When should WinningHunter or Minea be considered?", answer: "When Meta, TikTok or Pinterest ads, Shopify stores and competitor creatives are important inputs to the research process." },
      { question: "When is a team ready for automation?", answer: "When the manual process is stable, exceptions and owners are documented and failures can be detected and recovered." },
    ],
  },
  resources: {
    intro: "I organize the EcommerceIntel resource library around the evidence each of the five researched launch tools can provide. I do not list software simply to make the directory look larger, and I do not treat an affiliate relationship as a quality signal.",
    verdict: "I would shortlist Kalodata, FastMoss and Shoplus for different TikTok research jobs, and WinningHunter or Minea for advertising, products and stores. I keep official platform resources beside every third-party estimate because account records and current policies remain the verification layer.",
    sections: [
      { heading: "TikTok Shop Marketplace Intelligence", paragraphs: ["Kalodata is the clearest documented marketplace option because its public sitemap exposes category, shop, product, creator, video and livestream routes across multiple regional pages. FastMoss should be trialed for products, shops, creators, videos and market depth. Verify current plans and countries in both accounts.", "I would compare both products with a fixed entity set: one established product, one weak product, one shop, one creator and one video in every required market. The useful output is not a screenshot of an attractive ranking. It is a record of what each tool retrieved, the history it exposed, the fields labeled as estimates and the evidence another person can export or reproduce."] },
      { heading: "TikTok Content and Influencer Research", paragraphs: ["Shoplus's accessible official description focuses on popular TikTok videos, music, ads and influencers. This makes it useful for creative and creator discovery. Confirm any product, shop or estimated-sales modules separately before treating it as a full TikTok Shop intelligence replacement.", "For a content-led decision, I would record the recurring hook, demonstration, audience, creator type and format rather than copy a successful post. The research result should become an original brief grounded in verified product facts. Visibility inside a discovery tool does not establish reuse rights, commercial performance or permission to repeat another brand's claims."] },
      { heading: "Ad, Product and Store Intelligence", paragraphs: ["WinningHunter publicly describes Facebook Ad Library filters, TikTok ads, store tracking and competitor search. Minea covers Meta, TikTok and Pinterest ads, Magic Search, reverse image, supplier finding, brand tracking and Shopify store research.", "I would use known advertisers and products to compare retrieval, dates, history, landing-page evidence and estimated values before selecting one platform. I would also check whether the same researcher can return a week later and update the record without rebuilding it from memory.", "A persistent ad can justify deeper investigation, but it cannot confirm revenue, attribution, refunds or profit. I keep the public campaign record, the vendor's modeled fields and my interpretation in separate parts of the research note. That distinction matters when an interesting product moves into a budget or inventory decision."] },
      { heading: "Official Platform Resources", paragraphs: ["TikTok Shop Seller resources, Amazon Seller Central and the Shopify Help Center remain the verification layer for account, policy, listing, order and settlement questions. Third-party software can make external patterns easier to investigate, but it does not replace first-party account records.", "I treat an official source as the authority for what a platform permits and for what happened inside the seller's own account. Vendor documentation is the authority for the tool's stated product scope. EcommerceIntel's conclusion is editorial analysis of fit and remaining uncertainty. Keeping those three layers visible prevents a researched recommendation from being mistaken for a platform promise."] },
      { heading: "Evidence Levels Explained", paragraphs: ["Each review displays the level supported by its current evidence: direct testing, team use, feature research and operator workflow evaluation, or a narrower public information overview. Comparison-only inclusion is used when a product helps clarify a buying choice without supporting a full review.", "I leave a capability out when accessible evidence cannot support it. An evidence label is not a substitute for an account trial, and an official feature statement does not prove retrieval quality in a reader's country, category or plan."] },
      { heading: "How to Use a Resource Record", paragraphs: ["Open a record with one question and one representative entity. A TikTok Shop check might use a product, shop and creator already known in the target country; an ad-intelligence check might use a current advertiser and its live landing page. Record what the tool retrieved, what was missing and which values were estimates.", "Finish the record outside the research platform. Confirm account and policy questions in the official seller resource, capture the current plan and billing terms from the vendor, and attach margin or supplier evidence when the decision concerns inventory. This turns a tool link into an auditable operating reference."] },
      { heading: "Resource Record for Each Tool", bullets: ["Official and approved affiliate URL", "Category and best-fit workflow", "Research status", "Last checked date", "Current source pages", "Known data limitations", "Plan and market questions to verify", "Related review and comparison pages"] },
      { heading: "How to Maintain This Library", paragraphs: ["Update a tool only after checking its official homepage, pricing or plan interface and relevant feature pages. Record the new date and remove claims that can no longer be verified. Do not preserve outdated prices or market lists merely because they support an existing conclusion.", "A new category should appear only when it has a complete decision guide, useful tools, sources and internal links. Empty directory categories stay out of the public sitemap."] },
    ],
    faqs: [
      { question: "Why are only five tools featured?", answer: "The library favors complete, sourced review pages over a large directory of thin tool cards." },
      { question: "Which tools focus on TikTok Shop research?", answer: "Kalodata and FastMoss focus on marketplace intelligence, while Shoplus is most clearly documented around TikTok content, ads, music and influencers." },
      { question: "Which tools focus on ecommerce ads and stores?", answer: "WinningHunter and Minea connect advertising research with products, competitors and Shopify-oriented store intelligence." },
      { question: "Are these tools personally tested?", answer: "No. Their current status is Researched, and each review explains which official evidence was accessible and which claims still require a live trial." },
    ],
  },
  guides: {
    intro: "The guide library is organized around the decision sequence an ecommerce operator follows: understand the tool category, inspect one product, compare the shortlist and then apply a workflow. Every destination is published and internally connected.",
    verdict: "Start with one Pillar page, open the relevant Review, use a Comparison only after narrowing the shortlist and finish with a workflow that replaces estimates with actual operating evidence.",
    sections: [
      { heading: "Buying Guides", paragraphs: ["Buying guides explain the category and selection model. Use Best Ecommerce Tools for the full stack, Product Research Tools for marketplace and ad-led discovery, TikTok Shop Tools for entity-specific research, Ad Spy Tools for creative and advertiser intelligence, and AI Tools for controlled operational use cases.", "A buying guide should narrow the category. It should not function as a list of every vendor that could plausibly fit the keyword."] },
      { heading: "Tool Reviews", paragraphs: ["Each review has a separate factual basis. Kalodata uses its public sitemap and regional entity routes. FastMoss explicitly documents the public access limitation. Shoplus is evaluated from its TikTok analytics and influencer positioning. WinningHunter and Minea use their specific official feature pages and product descriptions.", "Read the review basis and limitations before the feature section. Feature research and public information overview do not imply hands-on account testing."] },
      { heading: "Comparison Pages", paragraphs: ["Kalodata vs FastMoss compares entity coverage, market depth, exports and plan fit without naming a permanent winner.", "Use known products, shops and creators in the comparison. A generic feature checklist cannot replace retrieval evidence."] },
      { heading: "Workflow Guides", paragraphs: ["How to Research Products for TikTok Shop takes the reader from market definition through category demand, creators, content, competitors, margin, supply and a small validation test. The workflow is where third-party estimates are converted into explicit questions and actual results."] },
      { heading: "Recommended Reading Paths", bullets: ["TikTok product researcher: Product Research Tools → Kalodata Review → Kalodata vs FastMoss → TikTok Shop Product Research", "Ad researcher: Ad Spy Tools → WinningHunter Review and Minea Review → representative advertiser trial", "New operator: Start Here → Ecommerce Tools → relevant platform or workflow", "AI evaluator: AI Tools → controlled four-week pilot"] },
      { heading: "How to Verify a Claim", paragraphs: ["Open the official source linked on the page and check whether it supports the exact capability, market or plan claim. Separate vendor statements from independently observable public routes and from EcommerceIntel's editorial judgment.", "When a source is blocked or inaccessible, the page should say so. Lack of access is not permission to fill the gap with a common feature list."] },
      { heading: "When a Guide Needs Updating", paragraphs: ["Update a page when a vendor changes markets, modules, pricing structure, credits, data sources or product positioning. Also update when the site's research status changes because a tool has been personally tested or used by the team.", "Remove stale claims rather than preserving word count. Content quality is measured by current decision value, not by historical length."] },
    ],
    faqs: [
      { question: "Where should a new reader begin?", answer: "Use Start Here to identify the current decision, then open one relevant buying guide." },
      { question: "What is the difference between a review and a comparison?", answer: "A review evaluates one product's capabilities and limitations. A comparison tests two shortlisted products against the same user and workflow." },
      { question: "Which guide explains TikTok Shop product research?", answer: "How to Research Products for TikTok Shop covers demand, shops, creators, content, pricing, supply and validation." },
      { question: "How are unverifiable claims handled?", answer: "They are omitted or explicitly labeled as requiring live verification. The site does not turn inaccessible documentation into an assumed feature." },
    ],
  },
};
