import type { ArticlePage } from "./pages";

const informationalPageFlags: Partial<ArticlePage> = {
  hideProsCons: true,
  hideDecisionSnapshot: true,
  hideOperatorView: true,
  hideWorkflow: true,
  hideFaq: true,
  hideSourceList: true,
  hideComparisonTable: true,
  hideFinalCta: true,
  hideNewsletter: true,
};

const policyPageFlags: Partial<ArticlePage> = {
  ...informationalPageFlags,
  hideQuickVerdict: true,
  hideDisclosure: true,
};

export const hubTrustFinalOverrides: Record<string, Partial<ArticlePage>> = {
  resources: {
    title: "Ecommerce Research Checklists and Resources",
    h1: "Ecommerce Research Checklists and Resources",
    description: "Use practical ecommerce product research, tool trial and ad research checklists, then open the relevant EcommerceIntel guide.",
    eyebrow: "Operator Resources",
    intro: "Use these checklists to turn research into a dated, reviewable decision. Each resource is short enough to copy into a spreadsheet or working brief.",
    verdict: "Start with the checklist that matches the next decision. A completed record is more useful than another unsorted list of tools or screenshots.",
    bestFor: [],
    watchFor: [],
    cardsHeading: "Choose a Practical Resource",
    cards: [
      { title: "TikTok Shop Product Research Workflow", label: "Workflow available", description: "Move from market definition to demand, economics, supply checks and a controlled test.", href: "/how-to-research-products-for-tiktok-shop", linkLabel: "Open the product research workflow" },
      { title: "Product Research Tool Shortlist", label: "Buying guide available", description: "Choose between marketplace-led and advertising-led research tools.", href: "/best-ecommerce-product-research-tools", linkLabel: "Compare product research tools" },
      { title: "TikTok Shop Tool Shortlist", label: "Buying guide available", description: "Compare tools for products, shops, creators, videos and livestream research.", href: "/best-ecommerce-intelligence-tools", linkLabel: "Compare TikTok Shop tools" },
      { title: "Ad Intelligence Tool Shortlist", label: "Buying guide available", description: "Compare paid research tools with official advertising libraries and manual checks.", href: "/best-ecommerce-ad-spy-tools", linkLabel: "Compare ad intelligence tools" },
      { title: "Kalodata vs FastMoss Trial", label: "Comparison available", description: "Run the same known-entity task in two TikTok Shop research products.", href: "/kalodata-vs-fastmoss", linkLabel: "Open the comparison" },
      { title: "Tool Directory", label: "Directory available", description: "Browse the software currently covered by a published EcommerceIntel decision page.", href: "/best-ecommerce-intelligence-tools", linkLabel: "Browse the tool directory" },
    ],
    sections: [
      {
        heading: "Download the CSV Templates",
        paragraphs: ["Open a blank CSV in Excel, Google Sheets or another spreadsheet tool. Each file uses the same fields shown in the checklists below and contains no signup, tracking gate or invented example data."],
        blocks: [
          { type: "internalLink", href: "/resources/product-research-brief.csv", label: "Download the Product Research Brief CSV", description: "Record demand, economics, supply checks, owner and stop condition." },
          { type: "internalLink", href: "/resources/tool-trial-comparison.csv", label: "Download the Tool Trial Comparison CSV", description: "Compare known entities, missing evidence, exports and subscription fit." },
          { type: "internalLink", href: "/resources/ad-creative-research.csv", label: "Download the Ad and Creative Research CSV", description: "Document public ad evidence and an original test concept." },
        ],
      },
      {
        heading: "Product Research Brief Checklist",
        bullets: [
          "Target country, category, customer and price band",
          "Customer problem and reason the offer could be different",
          "Demand evidence with source, date and observation window",
          "Shop, seller, creator, content or advertiser concentration",
          "Landed cost, fees, commission, advertising, returns and margin assumptions",
          "Supplier, documentation, packaging, fulfillment and policy checks",
          "Proceed, monitor or reject decision with an owner and deadline",
          "Small-test budget, success metric and stop condition",
        ],
      },
      {
        heading: "Tool Trial Comparison Sheet",
        bullets: [
          "The exact recurring question the subscription must answer",
          "Required markets, entities, date windows, seats and exports",
          "One known strong example and one known weak example",
          "Records found, important records missing and dates shown",
          "Estimate labels, source clarity and checks required outside the tool",
          "Time to produce a reusable brief and whether another operator can repeat it",
          "Current plan, billing cycle, renewal terms and cancellation route",
          "Keep, replace or postpone decision with the reason recorded",
        ],
      },
      {
        heading: "Ad and Creative Research Checklist",
        bullets: [
          "Advertiser, platform, market, landing page and observation date",
          "First-seen and last-seen dates where the source exposes them",
          "Hook, customer problem, proof, offer and call to action",
          "Repeated themes across several creatives rather than one isolated ad",
          "Official ad-library link or another primary public record",
          "Original test concept that does not copy protected creative or claims",
          "Budget, success metric and stop condition for the proposed test",
        ],
      },
      {
        heading: "Use the Correct Source of Truth",
        bullets: [
          "Platform policies, account status, orders and settlements: the relevant seller or advertising account",
          "Product costs, lead times, documents and quality: supplier records and samples",
          "Contribution margin and cash impact: the business's finance records",
          "Customer problems and returns: support, review and return records",
          "Competitor and market signals: dated third-party or public research, clearly labeled when estimated",
        ],
      },
    ],
    workflow: [],
    faqs: [],
    related: ["reviews", "best-ecommerce-intelligence-tools", "best-ecommerce-product-research-tools", "best-ecommerce-ad-spy-tools", "how-to-research-products-for-tiktok-shop"],
    ...informationalPageFlags,
  },

  tools: {
    title: "Ecommerce Research Tool Directory",
    h1: "Ecommerce Research Tool Directory",
    description: "Browse EcommerceIntel coverage of TikTok Shop, product research and ad intelligence tools by the job each product supports.",
    eyebrow: "Tool Directory",
    intro: "This directory includes tools with a published EcommerceIntel review or decision path. Choose by the research job, then confirm current features and plan limits on the official product site.",
    verdict: "Use one primary research product per recurring job unless a second tool produces a documented, non-overlapping output.",
    bestFor: [],
    watchFor: [],
    cardsHeading: "Browse Published Tool Coverage",
    cards: [
      { title: "Kalodata", label: "Full review available", description: "TikTok Shop products, shops, creators, videos and livestream research.", href: "/kalodata-review", linkLabel: "Read the Kalodata review" },
      { title: "FastMoss", label: "Full review available", description: "TikTok Shop entity and cross-market research evaluated against a known-entity workflow.", href: "/fastmoss-review", linkLabel: "Read the FastMoss review" },
      { title: "WinningHunter", label: "Full review available", description: "Advertising-led product and Shopify competitor research.", href: "/winninghunter-review", linkLabel: "Read the WinningHunter review" },
      { title: "Minea", label: "Full review available", description: "Cross-channel advertising, product, creative and store research.", href: "/minea-review", linkLabel: "Read the Minea review" },
      { title: "TikTok Shop Research Tools", label: "Buying guide available", description: "Compare published options by market, entity coverage and workflow fit.", href: "/best-ecommerce-intelligence-tools", linkLabel: "Open the TikTok Shop buying guide" },
      { title: "Official and Manual Checks", label: "Checklist hub", description: "Use platform records, official ad libraries and operator checklists before adding software.", href: "/best-ecommerce-intelligence-tools", linkLabel: "Open the research resources" },
    ],
    sections: [
      { heading: "TikTok Shop Research", paragraphs: ["Start with Kalodata or FastMoss when the weekly brief connects products to shops, creators and content. Compare the same known entities in every required country; do not choose from database-size or global-GMV headlines."] },
      { heading: "Advertising and Store Research", paragraphs: ["Start with WinningHunter for a focused advertising-to-Shopify workflow. Include Minea when cross-channel, image or broader store research is a recurring requirement. Official ad libraries remain the primary public verification layer."] },
      { heading: "What the Labels Mean", bullets: ["Full review available: a dedicated review page with a stated evidence basis", "Buying guide available: a category shortlist that compares several tools", "Checklist hub: a practical free or platform-native verification path"] },
    ],
    workflow: [],
    faqs: [],
    related: ["best-ecommerce-intelligence-tools", "best-ecommerce-intelligence-tools", "best-ecommerce-ad-spy-tools", "kalodata-vs-fastmoss"],
    ...informationalPageFlags,
  },

  about: {
    description: "Learn who publishes EcommerceIntel, how tool evidence is evaluated and how affiliate funding is kept separate from editorial judgment.",
    intro: "I created EcommerceIntel to help ecommerce operators choose software and build repeatable research workflows without treating vendor estimates as operating truth.",
    verdict: "The site combines cross-border ecommerce experience with clearly labeled evidence, direct operator judgment and transparent affiliate disclosure.",
    bestFor: [],
    watchFor: [],
    sections: [
      { heading: "Built from Ecommerce Operations", paragraphs: ["I am Elvis, an ecommerce operator with more than eight years of cross-border experience across TikTok Shop, Amazon, Shopify, Temu and SHEIN in US and European markets. My work has included product research, supplier coordination, creator outreach, advertising, content planning, store operations and turning research into briefs a team could execute.", "At peak operating periods, the ecommerce work I contributed to reached more than EUR 200,000 in monthly sales and about 5,000 monthly orders. Those figures describe peak periods across the operation. They are not stable averages, results attributed to one software product or a promise that another seller will achieve the same outcome."] },
      { heading: "How My Work Changed Across Platforms", paragraphs: ["Amazon work taught me to care about search demand, listing quality, fees, inventory and operational consistency. Shopify work made advertising, landing pages, contribution margin and creative testing more important. TikTok Shop added creator distribution, short-form content, livestreams and faster product cycles to the same commercial decision.", "Temu and SHEIN added another cross-border view: price pressure, assortment speed and supply-chain execution can matter as much as a demand chart. That is why EcommerceIntel does not rank software by the number of dashboards it provides. I look for the operating handoff the tool improves and the decisions it still cannot make."] },
      { heading: "A Typical Operating Decision", paragraphs: ["A promising product signal is only the beginning. I want to know whether demand is distributed, whether the content can be produced honestly, whether the supplier and documentation are workable, and whether landed margin survives advertising, commission, returns and fulfillment. A tool can help prioritize that investigation, but inventory and budget move only after the commercial checks are complete.", "This same discipline applies to software subscriptions. I start with one recurring question, test known entities, record missing evidence and keep the product only when it produces a clearer reusable brief. Feature count is less important than whether another operator can understand and repeat the decision."] },
      { heading: "How I Research and Judge Tools", paragraphs: ["I start with official product pages, documentation, pricing information and platform sources, then assess the workflow a tool supports, the evidence it exposes and the checks that still belong to the seller. Each page uses an evidence label appropriate to the material available, from personally tested work to public information or comparison-only inclusion.", "Product facts and editorial conclusions are kept separate. I do not invent prices, discounts, ratings, test results or performance figures. Third-party GMV, revenue, traffic and advertising values remain estimates unless a primary source identifies them as official. A tool earns a recommendation only when it fits a defined recurring decision and its limitations are acceptable."] },
      { heading: "Funding and Editorial Independence", paragraphs: ["Some outbound links may be affiliate links, which can generate a commission at no extra cost to the reader. Affiliate availability does not determine inclusion, evidence level or verdict. When no approved affiliate link exists, EcommerceIntel can link directly to the official destination.", "Material errors can be reported at hello@ecommerce-intel.com. Corrections should be based on current primary evidence, and commercial requests do not override the editorial record."] },
      { heading: "Where to Start", paragraphs: ["Open the Tools database when you know the research job but not the product. Use Reviews and Comparisons when a subscription is already on the shortlist. Use the TikTok Shop workflow when the immediate task is to turn product, shop, creator and content signals into a proceed, monitor or reject decision.", "Questions, corrections and relevant product evidence can be sent to hello@ecommerce-intel.com. I review factual corrections against current primary sources and update the affected conclusion when the evidence materially changes the decision."] },
    ],
    workflow: [],
    faqs: [],
    related: ["affiliate-disclosure", "privacy", "terms", "best-ecommerce-intelligence-tools"],
    ...informationalPageFlags,
  },

  "affiliate-disclosure": {
    description: "Read how affiliate links may fund EcommerceIntel without controlling tool inclusion, evidence labels or editorial conclusions.",
    intro: "Some EcommerceIntel links may be affiliate links. If you complete a qualifying action, I may receive a commission at no extra cost to you.",
    bestFor: [],
    watchFor: [],
    sections: [
      { heading: "How Affiliate Links Work", paragraphs: ["An approved tracking link may record that a visitor reached a vendor from EcommerceIntel. The vendor or affiliate network decides whether an action qualifies for commission. When no approved tracking link is enabled, the site uses the ordinary official destination."] },
      { heading: "Editorial Independence", paragraphs: ["Affiliate availability does not determine which tools are covered or recommended. Conclusions are based on the page's stated evidence, workflow fit, limitations and reader decision. A commercial relationship does not justify a positive verdict, invented rating, fake discount, urgency claim or statement of official partnership."] },
      { heading: "Link and Purchase Standards", paragraphs: ["Affiliate or sponsored links use appropriate sponsored and nofollow relationship attributes. Ordinary official links may use standard external-link attributes. Prices, plans, trials, renewal rules and cancellation terms can change, so confirm them on the official destination before buying. EcommerceIntel does not guarantee revenue, savings, approval or any other result from a product or affiliate link."] },
      { heading: "Questions", paragraphs: ["Questions about this disclosure can be sent to hello@ecommerce-intel.com."] },
    ],
    workflow: [],
    faqs: [],
    related: ["about", "privacy", "terms"],
    ...policyPageFlags,
  },

  privacy: {
    description: "Read how EcommerceIntel uses Google Analytics, handles cookies, external links, retention and privacy requests.",
    intro: "This policy describes the current public EcommerceIntel site. It does not operate a newsletter or account-registration form at the time of this review.",
    bestFor: [],
    watchFor: [],
    sections: [
      { heading: "Information You Provide", paragraphs: ["The site does not currently provide an email signup, account or comment form. If you contact EcommerceIntel directly by email, the message and contact details are used to respond, maintain necessary business records and handle legal or security issues. Do not send sensitive personal, payment or confidential business information unless it is necessary."] },
      { heading: "Google Analytics", paragraphs: ["EcommerceIntel uses Google Analytics 4 with measurement ID G-W85K9NCP1F to measure page views and defined interactions such as internal navigation, resource downloads and affiliate CTA clicks. When the Google tag is available, the site sends the event name and relevant page or link context to Google Analytics.", "Google Analytics may process the page URL, referrer, browser and device information, approximate location and interaction data. Google controls its own processing under its privacy terms. EcommerceIntel uses this information to understand site usage and improve content and navigation, not to guarantee an individual commercial result."] },
      { heading: "Cookies and Browser Storage", paragraphs: ["Google Analytics may use cookies or similar browser technologies to distinguish visits and measure usage. Visitors can use browser controls, cookie settings or Google-provided opt-out tools to limit this processing. External destinations may set their own cookies or use browser storage under their own policies."] },
      { heading: "Hosting, External Processors and Links", paragraphs: ["Google acts as the analytics provider, while hosting or infrastructure providers may process standard request and security data such as IP address, browser information, requested URL and timestamp to deliver the site, prevent abuse and diagnose failures. EcommerceIntel also links to product vendors, platforms and affiliate destinations; those organizations control their own sites, accounts, cookies and transactions.", "Review an external destination's privacy policy before creating an account, making a purchase or submitting personal or commercial information. EcommerceIntel does not control data collected after you leave this site."] },
      { heading: "Retention and Security", paragraphs: ["Analytics data is retained according to the settings of the EcommerceIntel Google Analytics property and Google's applicable policies. Hosting and security logs, if generated, follow the relevant provider configuration. Direct email correspondence is retained only while reasonably necessary for the request, business records, dispute prevention or legal compliance.", "Reasonable technical and organizational measures are used, but no website, analytics service, email system or external provider can guarantee absolute security."] },
      { heading: "Your Privacy Rights and Contact", paragraphs: ["Depending on your location, you may have rights to request access, correction, deletion, restriction or objection regarding personal data controlled by EcommerceIntel. You may also have the right to complain to a local data-protection authority. Send a request to hello@ecommerce-intel.com with enough information to identify the relevant correspondence. Identity may be verified before a request is completed."] },
      { heading: "Children and Policy Updates", paragraphs: ["EcommerceIntel is intended for ecommerce professionals and is not directed to children. The site does not knowingly solicit personal information from children. If you believe a child has provided personal data, contact hello@ecommerce-intel.com.", "This policy may be updated when forms, analytics, hosting, affiliate systems or other processing changes materially. The last-updated date shows when these terms were most recently revised."] },
    ],
    workflow: [],
    faqs: [],
    related: ["about", "terms", "affiliate-disclosure"],
    ...policyPageFlags,
  },

  terms: {
    description: "Review the terms governing informational content, intellectual property, external services and use of EcommerceIntel.",
    intro: "By using EcommerceIntel, you agree to these terms. The site provides general editorial and educational information, not legal, tax, financial, investment or platform-compliance advice.",
    bestFor: [],
    watchFor: [],
    sections: [
      { heading: "Scope and Acceptable Use", paragraphs: ["You may read and share links to EcommerceIntel for lawful personal or internal business research. Do not interfere with the site, bypass access controls, use abusive automated access, misrepresent an affiliation with EcommerceIntel or use the content to violate law or third-party rights."] },
      { heading: "Intellectual Property", paragraphs: ["EcommerceIntel's original text, selection, organization and branding are protected by applicable intellectual-property laws. You may quote limited portions with clear attribution and a link to the source. Republishing, selling, scraping or reproducing substantial content requires prior written permission. Product names, logos and trademarks belong to their respective owners."] },
      { heading: "Information and No Guarantees", paragraphs: ["Content is provided for general research and may become incomplete or outdated as products, prices, markets, policies and interfaces change. EcommerceIntel does not guarantee accuracy for a particular account, uninterrupted availability or suitability for a specific purpose.", "No article, tool, estimate, ranking or external link guarantees sales, profit, savings, advertising performance, product demand, account approval, platform eligibility or any other commercial outcome. Confirm material decisions with official sources and qualified advisers."] },
      { heading: "External Services and Affiliate Links", paragraphs: ["External products, subscriptions, accounts and transactions are governed by the provider's own terms and privacy policy. Review current price, billing cycle, renewal, cancellation, market coverage, data rights and permitted use before committing. EcommerceIntel is not responsible for an external provider's service, availability, content or transaction. Some links may generate an affiliate commission as explained in the Affiliate Disclosure."] },
      { heading: "Limitation of Liability", paragraphs: ["To the maximum extent permitted by applicable law, EcommerceIntel and its operator are not liable for indirect, incidental, special, consequential or business losses arising from use of, or reliance on, the site or an external service. Nothing in these terms excludes liability that cannot lawfully be excluded. Your use of the site remains at your own judgment and risk."] },
      { heading: "Changes, Suspension and Termination", paragraphs: ["Content, features and these terms may be changed as the site evolves. The last-updated date identifies the current terms. Access may be limited or terminated when necessary for security, maintenance, legal compliance or misuse. Provisions that by their nature should survive termination, including intellectual property and liability limits, continue to apply."] },
      { heading: "Governing Terms and Contact", paragraphs: ["These terms are governed by the laws applicable to the operator of EcommerceIntel, excluding conflict-of-law rules, except where mandatory law provides otherwise. Courts with lawful jurisdiction over the operator or dispute will apply. Before starting a formal dispute, contact hello@ecommerce-intel.com so the issue can be reviewed."] },
    ],
    workflow: [],
    faqs: [],
    related: ["about", "privacy", "affiliate-disclosure"],
    ...policyPageFlags,
  },
};
