import type { ArticlePage } from "./pages";

const estimateBoundary = "Vendor and third-party research data can be directional or estimated. I verify account, policy, order and settlement decisions in the relevant platform system and validate commercial decisions with margin, supply and controlled-test evidence.";
const platformBoundary = "I treat each seller account and official platform resource as the authority for current policies and operating records. External intelligence can guide investigation, but I confirm commercial decisions with first-party results, contribution margin, supply evidence and limited tests.";

export const toolsPage: ArticlePage = {
  slug: "tools",
  title: "Ecommerce Intelligence Tools by Research Workflow",
  h1: "Ecommerce Intelligence Tools",
  description: "Browse ecommerce intelligence tools by product research, TikTok Shop, competitor, advertising and store-analysis workflow.",
  eyebrow: "Tool Directory",
  kind: "hub",
  intro: "I organize tools by the decision they help an ecommerce operator make. This directory separates TikTok Shop marketplace research from advertising-led product discovery, competitor analysis and official platform verification.",
  verdict: "I would begin with one recurring research question and one representative test brief. Kalodata, FastMoss and Shoplus belong to TikTok-focused shortlists; WinningHunter and Minea belong to advertising, product and store research; platform-native systems remain the source of truth for account operations.",
  myView: "I do not treat a larger dashboard as a better tool. I look for reliable retrieval in the required market, clear estimate labels, useful history, exports that preserve evidence and a workflow another operator can reproduce. If a subscription cannot improve a named weekly decision, I would not add it to the stack.",
  bestFor: ["Operators comparing ecommerce research categories", "TikTok Shop product and creator teams", "Advertising and competitor research teams", "Agencies standardizing software evaluation"],
  watchFor: ["Overlapping subscriptions", "Estimated values presented as platform truth", "Market and plan limits", "Tools without an owner or recurring output"],
  cards: [
    { title: "Product Research", description: "Compare marketplace and advertising-led systems for candidate discovery and demand validation.", href: "/best-ecommerce-product-research-tools", label: "Buying guide" },
    { title: "TikTok Shop Intelligence", description: "Evaluate products, shops, creators, videos, livestreams and market coverage.", href: "/best-ecommerce-intelligence-tools", label: "Platform tools" },
    { title: "Advertising Research", description: "Study advertisers, creatives, landing pages, products and store connections.", href: "/best-ecommerce-ad-spy-tools", label: "Ad intelligence" },
    { title: "Tool Records and Sources", description: "Review official links, evidence boundaries, research status and current checks.", href: "/best-ecommerce-intelligence-tools", label: "Resource library" },
  ],
  sections: [
    { heading: "Choose a Tool Category from the Decision", paragraphs: ["I first write the decision, market, platform, responsible operator and output. Product discovery, creator research, ad analysis and store monitoring may look similar in a feature list, but they require different entities and verification steps. A category should narrow the software shortlist before a vendor demo begins.", "I also record exclusions. If the decision depends on account settlements, order defects, policy eligibility or actual advertising cost, a third-party intelligence platform cannot be the final source. The tool can identify questions and external patterns while the platform account and operating records confirm the answer."] },
    { heading: "TikTok Shop Marketplace Research", paragraphs: ["Kalodata and FastMoss are the closest marketplace-intelligence candidates in the current launch set. Compare them with known products, shops, creators and recent content in every required country.", "Shoplus is positioned more clearly around TikTok videos, music, ads and influencers. Compare its current commerce modules with the product, shop, sales-estimate and livestream depth required by the brief."] },
    { heading: "Product and Demand Research", paragraphs: ["A product-research system should produce a shortlist with dates, filters, sources and rejection reasons. I compare demand direction, seller concentration, creator or advertiser breadth, content activity and the age of the opportunity. I do not promote a candidate because one estimated GMV or sales field is large.", "The shortlist then moves into contribution margin, supplier reliability, product documentation, customer complaints, fulfillment and policy review. This second stage is where an attractive research signal becomes a controlled commercial hypothesis or is rejected before unnecessary inventory and advertising spend."] },
    { heading: "Advertising and Creative Intelligence", paragraphs: ["WinningHunter and Minea are relevant when the brief begins with Meta, TikTok or other supported advertising, products, advertisers, landing pages and Shopify-oriented store signals. I test known advertisers first so I can measure retrieval and history before trusting discovery in an unfamiliar category.", "Active ads, estimated spend and visible longevity do not establish profit. My output is an original creative brief that identifies repeated customer problems, demonstrations, proof structures and offers while preserving product truth and avoiding copied footage, scripts or brand assets."] },
    { heading: "Competitor and Store Research", paragraphs: ["I define the competitor entity before choosing software: marketplace shop, Shopify store, advertiser, product, creator or landing page. That definition determines whether a TikTok Shop platform, an ad-intelligence product or an official public library is the correct starting point.", "I keep observable facts, vendor estimates and my interpretation in separate fields. A store-traffic or revenue estimate can suggest relative direction, but it should not be reported as confirmed internal performance or used without margin, offer and channel context."] },
    { heading: "What I Record During a Trial", bullets: ["Required countries and known entities", "Date range, history and recency labels", "Missing products, shops, creators or advertisers", "Export format and evidence retained", "Estimate labels and methodology disclosures", "Time from question to reproducible output", "Plan, seat, credit and cancellation questions", "Verification work still required outside the tool"] },
    { heading: "Avoid Overlapping Subscriptions", paragraphs: ["Two tools can deserve a place when they answer separate recurring questions. A TikTok Shop entity platform and a cross-channel ad platform may support different owners and outputs. Two nearly identical dashboards are harder to justify when the team cannot explain how their evidence differs.", "Before renewal, I review the owner, current plan, recent assignments, exports used and decisions changed. If the subscription has become an occasional source of screenshots rather than a repeatable input, I would cancel it or redesign the workflow."] },
    { heading: "Official Systems Stay in the Stack", paragraphs: ["TikTok Shop seller resources, Amazon Seller Central and the Shopify Help Center belong beside third-party tools. I use them for current policies, account features and operating instructions because an intelligence vendor cannot override a platform's own terms or the data in a seller account.", "This boundary also improves content accuracy. I can use external research to explain patterns and selection criteria while linking a material platform requirement to the official source readers need to check at the time of action."] },
    { heading: "My Tool Selection Rule", paragraphs: ["I choose the smallest system that can complete the recurring brief with evidence another operator can review. The tool must retrieve the right entities, make limitations visible and reduce total research time without encouraging unsupported conclusions.", "I would postpone a purchase when the workflow is undefined, the target market cannot be demonstrated or the business expects software to guarantee a winning product. A disciplined spreadsheet and platform-native data can be the better first stack until research volume justifies another subscription.", estimateBoundary] },
  ],
  workflow: ["Write one recurring decision and required output.", "Select the marketplace, advertising, competitor or official-platform category.", "Run the same known-entity brief in two shortlisted products.", "Record retrieval, limits, exports, evidence quality and remaining verification.", "Adopt the smallest stack with a named owner and renewal rule."],
  faqs: [
    { question: "Which ecommerce intelligence tool should I start with?", answer: "Start with the platform and recurring decision. Compare Kalodata or FastMoss for TikTok Shop marketplace research and WinningHunter or Minea when advertising, products and stores lead the brief." },
    { question: "Should I subscribe to more than one research tool?", answer: "Only when each product has a separate owner, question and output. Overlapping dashboards usually increase cost and make estimates harder to reconcile." },
    { question: "Are third-party sales and GMV values official?", answer: "Do not assume they are. Treat them as estimates unless the provider identifies first-party provenance, and verify decisions with platform-native and operating evidence." },
    { question: "What should a tool trial prove?", answer: "It should retrieve known entities in required markets, preserve useful evidence, expose limitations and produce a repeatable decision faster than the current process." },
  ],
  related: ["resources", "platforms", "best-ecommerce-product-research-tools", "best-tiktok-shop-tools", "best-ecommerce-ad-spy-tools", "start-here"],
  toolKeys: ["kalodata", "fastmoss", "shoplus", "winninghunter", "minea"],
  disclaimer: estimateBoundary,
};

export const platformsPage: ArticlePage = {
  slug: "platforms",
  title: "Ecommerce Platforms and Tool Workflows",
  h1: "Ecommerce Platforms",
  description: "Choose research and operating workflows for TikTok Shop, Amazon and Shopify without mixing platform-native data with third-party estimates.",
  eyebrow: "Platform Hub",
  kind: "hub",
  intro: "I use this hub to separate the operating systems and research questions behind TikTok Shop, Amazon and Shopify. Each platform needs a different balance of first-party account data, external intelligence, content, advertising and operational control.",
  verdict: "Start with the platform where the order, listing or store decision occurs. Use external tools to investigate public patterns and create shortlists, then return to platform-native data for account, policy, inventory, advertising and settlement decisions.",
  myView: "I would not force one research stack across all three platforms. TikTok Shop connects products to creators and content; Amazon centers listings, keywords, advertising, reviews and inventory; Shopify gives the operator more control over the store, marketing stack and automation. The useful common layer is a documented evidence and validation process.",
  bestFor: ["Cross-platform ecommerce operators", "Teams choosing tools by sales channel", "Agencies standardizing platform handoffs", "Sellers separating external estimates from account data"],
  watchFor: ["Using a tool outside its strongest platform", "Ignoring current platform policy", "Mixing estimates with settlements", "Automating before exceptions are documented"],
  cards: [
    { title: "TikTok Shop", description: "Connect products, shops, creators, videos, livestreams and advertising to a validation workflow.", href: "/best-ecommerce-intelligence-tools", label: "Marketplace and content" },
    { title: "Amazon", description: "Keep Seller Central, listing, advertising, review and inventory records close to the decision.", href: "/best-ecommerce-product-research-tools", label: "Marketplace operations" },
    { title: "Shopify", description: "Combine store research, advertising, content, retention and automation around owned-store economics.", href: "/best-ecommerce-ad-spy-tools", label: "Owned storefront" },
    { title: "Cross-Platform Tool Directory", description: "Compare research categories and define which system owns each recurring question.", href: "/best-ecommerce-intelligence-tools", label: "All tools" },
  ],
  sections: [
    { heading: "TikTok Shop: Marketplace, Creators and Content", id: "tiktok-shop", paragraphs: ["TikTok Shop product research is not only a product table. I connect category direction and shop concentration to creators, videos, livestreams, offers and the team's ability to produce credible content. Kalodata, FastMoss and Shoplus support different parts of that external investigation.", "Seller Center and official TikTok Shop resources remain the authority for the account, current policies and operational records. I use third-party estimates to prioritize questions, then validate margin, fulfillment, returns, creator economics and actual results through controlled work."] },
    { heading: "Amazon: Listings, Advertising and Inventory", id: "amazon", paragraphs: ["Amazon decisions depend heavily on first-party account and marketplace evidence: listing eligibility, keyword and advertising reports, reviews, inventory, fees and order performance. I would not use a TikTok or Shopify intelligence product as a substitute for those records.", "External research can still help frame category, competitor, offer and creative questions. The handoff must be explicit: discovery creates a hypothesis, Seller Central and approved Amazon workflows confirm what applies to the account, and a margin model determines whether the opportunity is commercially workable."] },
    { heading: "Shopify: Store, Marketing and Automation", id: "shopify", paragraphs: ["Shopify gives an operator more control over merchandising, content, checkout, email, customer support and automation. WinningHunter and Minea can contribute advertising, product and store research, while Shopify's own help and admin systems define the actual store capabilities and records.", "I evaluate the full funnel rather than a competitor's estimated sales figure. The useful evidence includes offer structure, landing-page clarity, traffic source, contribution margin, customer retention and the correction work created by apps or automation."] },
    { heading: "Use the Right Source of Truth", paragraphs: ["I assign every important field to a source. Platform accounts own orders, settlements, advertising cost and account status. Supplier records own lead time and product evidence. Finance records own contribution margin. Research tools own the external observations and estimates they actually expose.", "This prevents a dashboard from becoming more authoritative than the system that processed the transaction. It also makes updates easier because the team knows where to refresh a policy, plan, estimate or actual result."] },
    { heading: "Build Platform-Specific Research Briefs", paragraphs: ["For TikTok Shop, I include products, shops, creators, videos and countries. For Amazon, I include category, listing, keyword, review, advertising and inventory questions. For Shopify, I include stores, products, offers, creatives, traffic hypotheses and retention workflows.", "The brief should name the decision deadline, hard constraints and evidence output. A common template is useful, but forcing identical metrics across platforms hides the relationships that make each channel different."] },
    { heading: "Cross-Platform Handoffs", bullets: ["Research shortlist to margin and supplier review", "Platform policy check before listing or launch", "Approved product facts to original content brief", "Advertising evidence to controlled creative test", "Actual orders, returns and support issues back into research", "Automation only after owners, exceptions and recovery steps are documented"] },
    { heading: "Choose Tools by Platform Fit", paragraphs: ["I test whether the tool retrieves the entities and history the platform workflow needs. Broad global positioning is not enough. A TikTok Shop agency may need creator and country depth; a Shopify advertising team may need historical creatives and store connections; an Amazon operator may need a platform-approved listing or keyword process.", "I also compare the output, not only the interface. The winning tool should produce a clear evidence record and reduce the time required to reach a defensible next step."] },
    { heading: "My Cross-Platform Rule", paragraphs: ["I keep platform-native systems at the center and use external intelligence around them. This reduces the risk of treating an estimate as settlement data, applying one platform's pattern to another or automating a process whose exceptions have not been understood.", "A cross-platform stack earns its place when each system has a specific owner, source boundary and handoff. If the same tool is retained for vague discovery across every channel, I would narrow its role or remove it.", platformBoundary] },
  ],
  workflow: ["Choose the platform where the operating decision occurs.", "List the platform-native records that own the answer.", "Add an external research tool only for a defined evidence gap.", "Validate the hypothesis with margin, policy, supply and controlled tests.", "Feed actual results back into the platform-specific research brief."],
  faqs: [
    { question: "Can I use the same research tool for TikTok Shop, Amazon and Shopify?", answer: "Sometimes, but the source-of-truth and entity requirements differ. Keep platform-native records central and test external tools against each channel's real brief." },
    { question: "Which platform needs creator and content research most directly?", answer: "TikTok Shop most directly connects marketplace products with creators, videos and livestreams, so those entities belong in the research brief." },
    { question: "What should an Amazon operator verify first?", answer: "Verify listing, advertising, review, inventory, fee and account questions through Seller Central and current official Amazon resources." },
    { question: "What makes Shopify research different?", answer: "Shopify gives the operator more control over the store and marketing stack, so research should connect products and competitor patterns to owned-store economics, retention and automation." },
  ],
  related: ["tools", "resources", "start-here", "best-tiktok-shop-tools", "best-ecommerce-product-research-tools", "best-ecommerce-ad-spy-tools"],
  disclaimer: platformBoundary,
};
