export type ReviewsDirectoryType = "reviews" | "comparisons" | "alternatives";
export type ReviewsDirectoryItem = {
  type: ReviewsDirectoryType; title: string; conclusion: string; bestFor: string; platform: string; evidence: string;
  assessment?: string; featured?: boolean; coverTone: "emerald" | "blue" | "coral" | "violet" | "cyan" | "amber"; coverMark: string; href: string;
};
export const reviewsDirectoryItems: ReviewsDirectoryItem[] = [
  { type: "reviews", title: "WinningHunter Review", conclusion: "Assess the ad-to-product and Shopify store research workflow.", bestFor: "Shopify-focused product and ad researchers", platform: "Meta, TikTok and Shopify", evidence: "Workflow evaluation", featured: true, coverTone: "coral", coverMark: "WH", href: "/winninghunter-review" },
  { type: "reviews", title: "Kalodata Review", conclusion: "Follow a TikTok Shop marketplace-first research path.", bestFor: "TikTok Shop sellers", platform: "TikTok Shop", evidence: "Workflow evaluation", coverTone: "emerald", coverMark: "KD", href: "/reviews/kalodata" },
  { type: "reviews", title: "TrendTrack Review", conclusion: "Review a trend-led product research workflow and its evidence limits.", bestFor: "Operators tracking categories over time", platform: "Trend and ecommerce research", evidence: "Public information overview", coverTone: "blue", coverMark: "TT", href: "/reviews/trendtrack" },
  { type: "reviews", title: "ShopHunter Review", conclusion: "Start with store and competitor research when that is the main question.", bestFor: "Shopify operators", platform: "Shopify stores", evidence: "Workflow evaluation", coverTone: "violet", coverMark: "SH", href: "/reviews/shophunter" },
  { type: "reviews", title: "PipiAds Review", conclusion: "Study an advertising-first product research workflow and its limits.", bestFor: "Performance marketers", platform: "Paid-social research", evidence: "Workflow evaluation", coverTone: "cyan", coverMark: "PA", href: "/reviews/pipiads" },
  { type: "comparisons", title: "WinningHunter vs Kalodata", conclusion: "Choose between ad-to-store research and TikTok Shop intelligence.", bestFor: "Teams choosing a primary research tool", platform: "Meta, Shopify and TikTok Shop", evidence: "Matched workflow comparison", featured: true, coverTone: "coral", coverMark: "WK", href: "/winninghunter-vs-kalodata" },
  { type: "comparisons", title: "WinningHunter vs PipiAds", conclusion: "Compare two advertising-led paths to product and competitor research.", bestFor: "Ad research teams", platform: "Paid-social research", evidence: "Matched workflow comparison", coverTone: "cyan", coverMark: "WP", href: "/winninghunter-vs-pipiads" },
  { type: "comparisons", title: "WinningHunter vs ShopHunter", conclusion: "Compare ad-first and store-first research workflows.", bestFor: "Shopify researchers", platform: "Ads and stores", evidence: "Matched workflow comparison", coverTone: "violet", coverMark: "WS", href: "/winninghunter-vs-shophunter" },
  { type: "alternatives", title: "WinningHunter Alternatives", conclusion: "Switch only for a named channel, market or workflow gap.", bestFor: "Teams considering a replacement", platform: "Ecommerce research", evidence: "Switching-reason guide", coverTone: "amber", coverMark: "ALT", href: "/winninghunter-alternatives" },
];
